### ISSUE TITLE
Run On Mac

### ISSUE THREAD

**Issue by ultimatemm** [WebVella/WebVella-ERP#102]
Hi,

How to run WebVella on Mac computer? :)

Thanks

**Comment by bzashev** [comment]
Hey,
thanks for asking that. The framework we are building the ERP upon is based on asp.net core 1.1 which should be able to run on PC, Mac or Linux, BUT currently we are also using some windows specific libraries as they are not yet available for the pure .net Core version (that runs on all OSes). This is in our roadmap, but not an immediate priority
