### ISSUE TITLE
MS SQL support

### ISSUE THREAD

**Issue by sid80210** [WebVella/WebVella-ERP#104]
Hi,

I know that you don't support MS SQL but could you please list the classes that I need to check to evaluate a porting on this DB?
I want to understand the required effort.

Thanks

**Comment by rumen-yankov** [comment]
Hello, 
Initially we thought to support database layer and be able to support multiple database, but we changed our decision on later project stage.

The 'WebVella.ERP.Database' namespace mainly contains most of the classes that work with database, but there are few other outside this namespace i can't name atm.  You should consider we are using a very specific JSON PostgreSQL supported functionality, that may not be implemented on other database engines. 

Here is a sample: we can request for records from primary table and include relative rows from second on foreign key relation. Normally this is done by joins or separate database requests for each primary table record. In our case we build a JSON result that for each record with array property storing related (second) table rows and with one request we get exact result we need. If we use joins, the result recordset will be a flat and later we have to process it on logic, but we also have to consider that recordset size which increases cause the rows count will be multiplication between primary and relative table records requested. 

I hope the information will help you to you Sorry about my English
