### ISSUE TITLE
Compile Error in VS 2017

### ISSUE THREAD

**Issue by Rodan81** [WebVella/WebVella-ERP#108]
When I was trying to compile soultion from Visual Studio 2017 I got an error:

"Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='dnx46'. They must be specified explicitly.	
WebVella.ERP.Web	
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets"

Your help is really appreciated

**Comment by bzashev** [comment]
The solution is not still converted to 2017, so errors are expected.
We will convert it in the next months, try it again than, or open it with VS 2015 now.
