### ISSUE TITLE
Database creating error - postgreSQL

### ISSUE THREAD

**Issue by Rodan81** [WebVella/WebVella-ERP#110]
The application can not create the database needed to start and run.
I am using **Visual studio 2015 + Windows 10 Pro + PostgreSQL 9.6.3, 64-bit**

The ERP.Web application thrown exceptions such as:
**- 42P01: relation \"files\" does not exist**
**- Entity with such Id does not exist.**

Code in line 38 in file **WebVella.ERP.ERPService.cs**:
 **DbSystemSettings storeSystemSettings = DbContext.Current.SettingsRepository.Read();**
it returns **null** value and then **currentVersion = 0**.
What about the codes in the same file:
if (**currentVersion** < 150508) ................
if (**currentVersion** < 20160430)................
if (**currentVersion** < 20170125)................
if (**currentVersion** < 20170425)  ......................

**What shall I do to create databse without exceptions?**
**Is there an external script to create database?**

**Comment by rumen-yankov** [comment]
Hi, 
Unfortunately I am unable to simulate the error using exactly the same environment you described (Visual studio 2015 + Windows 10 Pro + PostgreSQL 9.6 64 bit).  Note that initial database create and applying patches to it (the currentVersion comparison in your description is related to patches) takes considerable time (depending on hardware and network connectivity to database). In my case it took about 2 and a half mins. Can you do one more try please following these steps:
1. Get ERP latest source from github
2.  Create an empty database. 
3. Change connection string in config.json in **WebVella.ERP.Web** project
4.  Set the project **WebVella.ERP.Web** as startup project in visual studio 
5. Run in debug configuration and wait 2-3+ mins

If the login screen appear everything should be ready.

**Is there an external script to create database?**
No, we don't have any external scripts. We create and patch database using the ERP api.
