### ISSUE TITLE
Request for support to new project

### ISSUE THREAD

**Issue by tomakali** [WebVella/WebVella-ERP#111]
Hi, your erp framework is good.
would you be interested to create fork of another popular erp?

there is a well established saas called fedena.com
i could not find a dotnet version of opensource alternate to fedena.com

there is a good dotnet framework called MixERP
but it is retail in nature

it would be great if you guys can use MixERP to create a clone of fedena.com like saas
[https://mixerp.org/forums/thread/592/mixerp-retail-and-mixerp-education-builds](url)

**Comment by bzashev** [comment]
Hey,
no interest in that. We are very far along in the core infrastructure to change the project right now.
You can help us by sharing, what are the best features in fedena that you want to see in our ERP.

Thanks,
Boz
