### ISSUE TITLE
How to use the record tree？

### ISSUE THREAD

**Issue by xiaofeng-123** [WebVella/WebVella-ERP#114]
No record is selected as the root node？

**Comment by bzashev** [comment]
Hey, 
the record tree is intended to create a category like tree structures. Lets say you want a category tree. First you need a category entity and a list of a records in this entity. Important is to have a parent ID identifier field in each record. Than you need to navigate to the administration -> the category entity -> create new tree. There you will define some meta for the tree so it can be generated exactly as you want it. Once you created that tree you can review a data sample in the same section of the administration. Afterwords you can use and get this tree whenever you need it using the web API or API methods and the system will generate the records in the "category" entity in a tree structure for you. Of course you can use it for categories or for menus or whatever you need

**Comment by xiaofeng-123** [comment]
Hi，I have created the record tree，but show the information of“No record is selected as the root node”?
And how to use the API？

**Comment by xiaofeng-123** [comment]
![1](https://user-images.githubusercontent.com/32192048/32759248-5da0e582-c923-11e7-8c97-7ce2797ab9e7.png)

**Comment by xiaofeng-123** [comment]
I now want to use it to develop ERP, but an order with order number, order name, etc., the order includes the product name and specifications in the library, but the corresponding number is definable, I use the record list lookup View to choose, but the corresponding number of no way to define, so I would like to choose to use the record tree to achieve these functions.

**Comment by bzashev** [comment]
You need to select the record or records that need to be considered the starting branch of the tree. From there on Parent/child relation is unfolded to create the tree. If you have let's say an ecommerce site and the three is the product categories, than the root nodes are the categories - Man, Women, Kid and from there you have Man -> Clothes, Man -> Shoes and etc, as well as Women -> Clothes, Women -> Shoes and etc
