### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by kwebmaster** [WebVella/WebVella-ERP#115]
Hi,

I have seen you project and it's really intereseting.
When do you plan to release a stable version (for production use) of you ERP, CRM and Project?

Thank you

**Comment by bzashev** [comment]
We already use it for production ourselves. The reason that it is not yet officially released is an undergoing change of the ERP interface UI. We are changing Angular to a better alternative with RazorPages and View Components

**Comment by bzashev** [comment]
This will be expected to be released with a number of components and documentation in Q1 of 2018. The Platform's core api though is ready and we do not plan to make significant changes, We will soon start uploading the new UI
