### ISSUE TITLE
Just Thought

### ISSUE THREAD

**Issue by samdubey** [WebVella/WebVella-ERP#118]
I have been using https://github.com/volkanceylan/Serenity/ for most of my line of business application development it is fast and well architect-ed framework.

I would like to see if this project could be using some components from the above open source project as it cuts down development time very short.

This is just a suggestion, I do not want to harm any ones sentiments here

**Comment by bzashev** [comment]
Hey,
thanks for the link. We will review it to check what can be done. Good ideas are always welcomed, so no worries.
