### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by parnupongk** [WebVella/WebVella-ERP#119]
we try to run ERP but error this 

NullReferenceException: Object reference not set to an instance of an object.
WebVella.Erp.Web.ErpMvcServicesExtensions.UseErpPlugin<T>(IApplicationBuilder app) in ErpMvcExtensions.cs, line 119

NullReferenceException: Object reference not set to an instance of an object.
WebVella.Erp.Web.ErpMvcServicesExtensions.UseErpPlugin<T>(IApplicationBuilder app) in ErpMvcExtensions.cs
+
                    service.Plugins.Add(plugin);
WebVella.Erp.Site.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in Startup.cs
+
			app
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

we can't resolve this error. please recommend

**Comment by rumen-yankov** [comment]
Hello, 
Can you provide more information please ? Which project you try to start ? Have you changed anything and what if you did ?

**Comment by rumen-yankov** [comment]
No response with more information. Closing.
