### ISSUE TITLE
Unable to see CRM application

### ISSUE THREAD

**Issue by tuanv2t** [WebVella/WebVella-ERP#120]
Hi bzashev,
I've found your project today and it's really great. I were eager try to run but unable to see crm application.

![29eec4c280de988abc044a9628b53a01](https://user-images.githubusercontent.com/8486393/61790714-28f91d80-ae42-11e9-9a30-b733cf789090.png)

Is there any plan to remove it or there's any issue, thank you for your help.

**Comment by bzashev** [comment]
Hey,
Crm is just a shell currently. You can see it if you load the CRM project as a startup.
