### ISSUE TITLE
The IntelliSense Download has been loading for a long time.

### ISSUE THREAD

**Issue by it19862** [WebVella/WebVella-ERP#121]
The IntelliSense Download has been loading for a long time.
I waited more than 15 minutes, and the download continues.

Is there any need to wait for this download of "IntelliSense Download"?

![image](https://user-images.githubusercontent.com/18245828/62703471-00505680-b9f2-11e9-97f5-b99ea433a143.png)

**Comment by rumen-yankov** [comment]
I am closing this issue cause its same or related to https://github.com/WebVella/WebVella-ERP/issues/122
