### ISSUE TITLE
How to run the application?

### ISSUE THREAD

**Issue by it19862** [WebVella/WebVella-ERP#122]
How to run the application?

The "IntelliSense Download" has been loading for a long time.
I waited more than 15 minutes, and the download continues.
![62703471-00505680-b9f2-11e9-97f5-b99ea433a143](https://user-images.githubusercontent.com/18245828/62703740-85d40680-b9f2-11e9-8edd-782a83bc7b15.png)

Despite this, I clicked on "F5".

I got.
![2019-08-08_15-26-34](https://user-images.githubusercontent.com/18245828/62703676-5fae6680-b9f2-11e9-9a6b-cb446e099a4b.png)

**Comment by rumen-yankov** [comment]
Hey,
What version of visual studio you use ? Did you try to close the msvs  and open the solution again ? 
I am trying to reproduce your problem. Made a fresh clone from github, loaded, build and run with no problems using the MSVS 2019.

**Comment by rumen-yankov** [comment]
I see that you are trying to run a library type project. Change the startup project to WebVella.Erp.Site

**Comment by it19862** [comment]
@rumen-yankov 
I use:
  - win 7x64;
   - VS 2019;

Downloaded the project "WebVella-ERP" to the computer.
Launched VS.
He opened the project "WebVella-ERP".
Dependencies updated.
Pressed F5.

The project is starting.

But there is another problem, I will describe in a separate issue.
