### ISSUE TITLE
How to start the application "WebVella.Erp.Site"?

### ISSUE THREAD

**Issue by it19862** [WebVella/WebVella-ERP#123]
Used by:
- Win 7 x64;
- VS 2019 Community;
- PostgreSQL - 11.

1. Developer. In "PostgreSQL" I created the base "boz_test".
2. Developer. I fixed the file - "Config.json".
```
Server=127.0.0.1;
 Port=5432;
 User Id=postgres;
 Password=admin;
 Database=boz_test;
 "FileSystemStorageFolder": "\\\\127.0.0.1\\Share\\erp3-files",
```
3. Developer. I assigned the project "WebVella.Erp.Site" to "Set as Startup Project"
4. Developer. I pressed F5.
5. Code. The code in PostgreSQL created 21 tables.
6. VS. VS finished debugging.
7. Developer. I pressed F5.
8. VS. VS opens the address - "http: // localhost: 40184 / login? ReturnUrl =% 2F".
9. Chrome. Chrome opens a blank page.
```
Unable to access the site. Connection dropped.
Try the following:

Check your internet connection.
Check your proxy and firewall settings.
Run network diagnostics on Windows
ERR_CONNECTION_RESET
```
10. VS. VS closes Chrome.
11. VS. VS itself finishes debugging.

**Question.**
How to start the application "WebVella.Erp.Site"?

**File - "Config.json"**
```
{
  "Settings": {
    "ConnectionString": "Server=127.0.0.1;Port=5432;User Id=postgres;Password=admin;Database=boz_test;Pooling=true;MinPoolSize=1;MaxPoolSize=100;CommandTimeout=120;",
    "EncriptionKey": "BC93B776A42877CFEE808823BA8B37C83B6B0AD23198AC3AF2B5A54DCB647658",
    "Lang": "en",
    "Locale": "en-US",
    "TimeZoneName": "FLE Standard Time",
    "CacheKey": "123",
    "DevelopmentMode": "true",
    "EnableBackgroungJobs": "true",
    "EnableFileSystemStorage": "false",
    "FileSystemStorageFolder": "\\\\127.0.0.1\\Share\\erp3-files",
    "EmailEnabled": false,
    "EmailSMTPServerName": "",
    "EmailSMTPPort": "25",
    "EmailSMTPUsername": "",
    "EmailSMTPPassword": "",
    "EmailFrom": "",
    "EmailTo": "",
    "AppName": "WebVella Next",
    "NavLogoUrl": "",
    "SystemMasterBackgroundImageUrl": ""
  },
	"Development": {
		"TestEntityName": "test",
		"TestRecordId": "001ea36f-fd2e-4d1b-b8ee-25d32d4e396c"
	},
	"ApiUrlTemplates": {
		"FieldInlineEdit": "/api/v3/en_US/record/{entityName}/{recordId}"
	}
}
```

**Database "boz_test".**
![devenv_2019-08-09_08-22-21](https://user-images.githubusercontent.com/18245828/62756911-24f40f00-ba82-11e9-88d9-3eadf623441c.png)

**Comment by rumen-yankov** [comment]
Sorry I am unable to reproduce the error in my development environment.  I am not sure is it related to windows 7 version, but can you try on windows 10 ?

**Comment by BlazorT** [comment]
Me too unable to start site

**Comment by BlazorT** [comment]
I can run it, Please make it clear, if Modules like Sale, Account, HRM, Purchase would be available..?

**Comment by rumen-yankov** [comment]
Probably in future, but not soon.
