### ISSUE TITLE
没有数据库吗，没有找到数据库

### ISSUE THREAD

**Issue by tmy8250** [WebVella/WebVella-ERP#124]

**Comment by bzashev** [comment]
Please check you connection string and whether the database is created in PostgreSQL. If this is ok, check the user and the password if it has admin access to the database

**Comment by tmy8250** [comment]
数据库是运行项目里的哪一个子项目来创建数据库的吗，看到了数据库的连接配置，但是没有找到数据库文件

**Comment by rumen-yankov** [comment]
Sorry, we don't understand Chinese language and the last comment is translated by google translate poorly. Can you write it in English or use simple sentences not that hard to translated by google.

**Comment by tmy8250** [comment]
Is the database running any sub-project in the project to create the database? You see the connection configuration of the database, but you can't find the database file.

**Comment by rumen-yankov** [comment]
You need to create manually an empty postgres database. On first ERP start it will create and initialize its structures and data.

**Comment by tmy8250** [comment]
Thank you

**Comment by tmy8250** [comment]
Can it only be a Postgres database? Is MSSQL OK?

**Comment by rumen-yankov** [comment]
Only Postgres is supported.

**Comment by tmy8250** [comment]
Postgres database installation database connection configuration: Connective String ":" Server = 172.16.10.110; Port = 5432; User Id = postgre; Pasword = test; Database = erp3_nexus; Pooling = true; MinPoolSize = 1; Max PoolSize = 100; Common Timeout = 120; ",,
When running a single step debugging, there is a transaction.connection = 'transaction.connection' an exchange of information 'and Npgsql.PostgresException:“28000: û���������� "172.16.10.110", �û� "postgre", ���ݿ� "erp3_next", SSL �ر� �� pg_hba.conf ��¼”

**Comment by rumen-yankov** [comment]
The connection string looks right. I suppose there is something specific related to your postgres server configuration that causes a problem (which i don't understand and need more information about it).

**Comment by tmy8250** [comment]
Is there anything you need to do to connect to vs after the Postgres database is installed?

My Postgres database was installed without any other configuration, that is, the password was set. The default user name of the Postgres database is postgre, right?

**Comment by rumen-yankov** [comment]
After you create an empty database and run the application for first time, it will create its structures and data. Nothing more than a new empty database is needed, no special database configuration is needed.

**Comment by tmy8250** [comment]
I just installed the database and then created a blank database.

**Comment by rumen-yankov** [comment]
look here https://stackoverflow.com/questions/44161509/message28000-no-pg-hba-conf-entry-for-host-xx-xxx-xxx-xxxx-user-user  this may help you resolve the error

**Comment by tmy8250** [comment]
What is the default login password when the login page opens

**Comment by rumen-yankov** [comment]
email "erp@webvella.com" and password "erp" 
You can find more information about getting started at https://webvella.com/documents/developer/introduction/getting-started
