### ISSUE TITLE
How to run WebVella.Erp.Web?

### ISSUE THREAD

**Issue by BlazorT** [WebVella/WebVella-ERP#126]
Need to know about steps and how to run WebVella.Erp.Web for erp running in browser..?
Note: Database configured and created, Seed is running. When I try to run said module it gives erro "Unable to run your project. the "RunCommand" property is not ..."

**Comment by BlazorT** [comment]
Finance , Sale, Purchase these modules are part of it..?

**Comment by todoru** [comment]
WebVella.Erp.Web is class library(can not be set to "run in browser"), you should set WebVella.Erp.Site as startup project. More info on how to get started and other questions you may have you can find [https://webvella.com/documents/developer/introduction/getting-started](here)

**Comment by Keith-Ocitti** [comment]
So I have followed every step necessary to setup the project and also set WebVella.Erp.Web as my startup, and I am able login.
But after there, the moment I click the Projects menu, I get errors, and can't navigate to it.

---the error-----
Exception User-Unhandled
System.InvalidOperationException: 'A view component named 'PcProjectWidgetTasksChart' could not be found. A view component must be a public non-abstract class, not contain any generic parameters, and either be decorated with 'ViewComponentAttribute' or have a class name ending with the 'ViewComponent' suffix. A view component must not be decorated with 'NonViewComponentAttribute'.'

![Image](https://github.com/user-attachments/assets/6ee7de81-26e6-46be-8318-ae30a9892115)
