### ISSUE TITLE
Using core 3.0 AssemblyLoadContext to Implement Plug-in Hot Loading

### ISSUE THREAD

**Issue by ghd258** [WebVella/WebVella-ERP#130]
Using core 3.0 AssemblyLoadContext to Implement Plug-in Hot Loading

**Comment by rumen-yankov** [comment]
Fixed. Update to latest nuget packages

**Comment by rumen-yankov** [comment]
We will experiment with new AssemblyLoadContext  supported funcionality for loading and unloading assemblies. When there is any progress we will write about it cause the change is going to be breaking.

**Comment by ghd258** [comment]
I've also tested that there's no need to restart  no restarting the website
https://www.cnblogs.com/lwqlun/p/11260750.html
https://github.com/lamondlu/Mystique
