### ISSUE TITLE
Unable to c any other modules except Software Development Kit  

### ISSUE THREAD

**Issue by nivogroup** [WebVella/WebVella-ERP#131]
Hi
I have done all the needful but it is only showing "Software Development Kit" unable to c project management or crm etc. Am I missing something

![error](https://user-images.githubusercontent.com/40050786/67631341-dd2f9780-f8ba-11e9-9451-e649db2f4b2a.png)

Thanks
Sidd

**Comment by bzashev** [comment]
Hey, no you are not missing anything. Currently the other modules are not available. But you can use the SDK to create whatever you need. There is a Project Mangement APP but it is just a sample
