### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by weedkiller** [WebVella/WebVella-ERP#136]
Hello, I wanted to help create a centralized page to both easy, feedback and help you with the best tools to get easy troubleshooting or ready to go libraries. We can link to actions.

- New Microsoft [PerfView](https://github.com/microsoft/perfview), VERY helpful
- Left Navigation _option_: Like WP can we allow users admins to admin WebVella on the left side, grouped in sections, its more intuitive.
- Plugin Showcase: Plugin market or list of plugins gallery like WP. 
- Roles and Claims or Groups, can we allow security based on groups inside a role. For e.g. Asia managers can only see Asia Salaries, US managers role can only see US salaries.
- Code generator skeleton for plugins, themes.
- Option to [pre-compile view](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1) or use HTML Agility Pack (pre compiling made the site load faster)
```
             //Install the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation NuGet package.
             //Update the project's Startup.ConfigureServices method to include a call to 
                        AddRazorRuntimeCompilation. 
                        public void ConfigureServices(IServiceCollection services)
                         {
                              services.AddRazorPages()
                .             AddRazorRuntimeCompilation();    
                         }
```
__________________

- Identity G[UI & Multi-tenant](https://github.com/skoruba/IdentityServer4.Admin)
- [Dashboards  Asp Sample](http://bit.ly/2G4hAkM) & settings [image](http://bit.ly/2Pj8kfa)

**Comment by bzashev** [comment]
Let me think about them for some time and I will feedback what and how

**Comment by weedkiller** [comment]
Sure, 😃  just suggestions, and place holder while you think about it.

**Comment by weedkiller** [comment]
Any chance you can add a `Roadmap & Milestones` with feature priority.
Also a catalog of plugins, so others can develop and share [WebVella plugins ](https://wordpress.org/plugins/) like WordPress

**Comment by weedkiller** [comment]
Hello, It would benefit if can you please add a simple diagram showing components/objects/architecture

1. What we need to implement to build our own plugin/entities
2. And where they would tie in with WebErp (use Blue for what the developers need to implement & Green for WebErp)

**Comment by bzashev** [comment]
The corresponding pages are
https://webvella.com/documents/developer/plugins/create-your-own
https://webvella.com/documents/developer/components/create-your-own

Diagrams would be nice yes
