### ISSUE TITLE
Default Postgres Driver Npgsql.net

### ISSUE THREAD

**Issue by weedkiller** [WebVella/WebVella-ERP#137]
Hello, I would like to suggest https://www.npgsql.org/ [maintained actively here on github](https://github.com/npgsql/npgsql)  devart is 3 yrs old, _but this is maintained directly by Postgres_ 10 days old

1. Also include it as a native package directly.
2. After installing in Visual Studio, just selection connection string from properties and paste into WebVilla-seed and WedVilla-Erp config.json file directly. 

![image](https://user-images.githubusercontent.com/21086190/71313019-125eee80-2401-11ea-9d29-c9a3fe056f1f.png)

**Comment by bzashev** [comment]
We will check it out and get back with feedback. If it is better no reason not to use it.
Thanks for all your great feedback :). 
Some nice ideas which will sure be helpful

Boz

**Comment by rumen-yankov** [comment]
Hello weedkiller, 
I am trying to understand what you want, but can't.  Can you please be more specific ?
Thanks in advance.
Rumen

**Comment by weedkiller** [comment]
Hello, I am simply _suggesting_ we switch & bundle native drivers to the native PostGres. This would easily allow new comers and developers to copy and paste connection string.

Many developers, like me, may come from MS Sql Server or MySql, and if they have to setup WebVella with PostGres _they may stumble._ I did, but figured it out and wanted to paste those instruction on your Github Wiki page, but it would not let me edit.

Another suggestion - what if we were database independent like so using something this [lib](https://github.com/sebastienros/yessql) or DB Blueprints if you are familiar with that.
