### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by j209** [WebVella/WebVella-ERP#138]
Does webvella support [blazor](https://github.com/aspnet/Blazor)?

**Comment by bzashev** [comment]
Currently not out of the box, but it can be added very easily. Also soon we plan to create a whole bunch of blazor components.

**Comment by ghd258** [comment]
Blazor support

**Comment by ghd258** [comment]
When to Blazor support

**Comment by bzashev** [comment]
Hey, so Blazor is supported very easily. The way we are doing it is the following:
1. We are creating a Razor Page with a url from the application page type like "/your-app/a/page-name/{*url}"
2. In this page we are injecting the Blazor script and the Blazor <app><component> as it was a normal page
3. We usually include some CSS and JS for our Blazor dediacated WebVella.Pulsar component library.

That's it

**Comment by ghd258** [comment]
Blazor support  When   time？

**Comment by rumen-yankov** [comment]
Hey ghd258,
We already support Blazor (server) as bzashev described the steps to create blazor app in previous comments. We plan to start implementation of SDK plugin entirely on Blazor, but this is a future task when we have time for it.
