### ISSUE TITLE
Setting JobContext.Result crashes 

### ISSUE THREAD

**Issue by 628426** [WebVella/WebVella-ERP#142]
Setting context.Result from within a job works perfectly and the table is populated with the right detail.

When this happens though, the following route crashes /sdk/server/job/l/list with an issue casting from System.string to Dynamic.  I don't know enough about automapper to investigate and there was inversion of control making it hard for me to find the exact code causing the problem.

If you do get around to fixing this, showing the result on the page (/sdk/server/job/l/list) might be helpful too I noted there was no column to show the result.

.Result is a super useful feature so I hope to be able to use it at some point.

The following code might explain it a bit more.

```c#
    [Job("C79A1A73-B4FE-4DAA-ACA0-74ECEF0C259C", "Reproduce", true, JobPriority.Low)]
    public class ReproJob : ErpJob {
        public override void Execute(JobContext context) {
            using (SecurityContext.OpenSystemScope()) {
                context.Result = "Some text here to describe the results of the job"; // this makes /sdk/server/job/list crash
            }
        }
    }
```

**Comment by rumen-yankov** [comment]
Added result wrapper so Json.Net can handle serialization and deserialization.
