### ISSUE TITLE
Use WebVella.Erp from a Console application

### ISSUE THREAD

**Issue by 628426** [WebVella/WebVella-ERP#145]
Is running WebVella from a Console application supported?  It would be helpful to use WebVella in particular EQL/EQLCommand and RecordManager with the the HookAttachments from a Console application or at least a ASP.NET Core environment where WebVella wasn't running background jobs, hosting controllers and web api calls and all those things that increase overheads and surface area.

The use case is using EQL Commands to list and RecordManager to update and create records from within an AWS Lamba Function or Scheduled Task, making use of logic in IErpPostCreateRecordHook

**Comment by rumen-yankov** [comment]
Hello Nathan, 
I added new WebVella.Erp.ConsoleApp project with sample how to initialize the erp engine, execute EqlCommands and how to attach record hooks. If you have any other additional questions or request about it please write me back.

**Comment by rumen-yankov** [comment]
Also there is configuration option in config.json EnableBackgroungJobs, which can be set to false and background jobs won't be executed even in web hosted env.
