### ISSUE TITLE
SDK PlugIn:  Delete Entity confirm('Are you sure?') still deletes the entity when Cancel selected

### ISSUE THREAD

**Issue by 628426** [WebVella/WebVella-ERP#148]
When clicking Delete Entity in the SDK, a javascript Are you sure? confirm appears.

If you click Cancel, it still deletes the entity! 

I looked into the code and couldn't find the offending line number or else I would have just fixed it.  Following is a screenshot from the chrome developer tools.  The onclick doesn't seem to use preventDefault or return false if Cancel is clicked..

![image](https://user-images.githubusercontent.com/610683/90947821-4ac93780-e47c-11ea-8c9f-5d968fe53d63.png)

**Comment by bzashev** [comment]
Fixed. Get the new package -> WebVella.Erp.Plugins.SDK.1.1.0

**Comment by 628426** [comment]
Thanks @bzashev
