### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by nguyen14ck** [WebVella/WebVella-ERP#150]
Hi!
Thanks for the worthy project.
Besides Postgresql, could we have another option using Ms Sql Sever?  

It would grow faster if we can port all the existing functions of MixERP to WebVella-ERP.
[https://github.com/mixerp/mixerp](MixERP)

Many thanks.

**Comment by 628426** [comment]
Hi @nguyen14kc, thanks for stopping by.  This is a downvote from me although I am not one of the maintainers.  postgresql runs everywhere as a first class supported database including, Azure, AWS, Google, Heroku and on most web hosting companies.  SQL would limit where the product can run.

I would also say that developing modules for WebVella does not use any database specific functionality

**Comment by bzashev** [comment]
Hey,
I would say that Postgres is a very good option. We work with it long years now. The tools are getting better and I am very pleased with it. I think it will be better to stick with it.

**Comment by nguyen14ck** [comment]
Thanks for your replies.
From the the technical view, Postgre is an ideal  and free option. From the market view, I suggest that because this projects uses Microsoft technology. There are so many open source ERP projects use Postgre. Besides Postgres, supporting Sql Server makes the project distinct and catch more users. That's what I saw with MixERP road map: "Due to popular demand, MixERP 2.0 will also support SQL Server..."
Best.

**Comment by weedkiller** [comment]
I agree with postgress, but Sql has a free version and it runs on Linux as well now.

**Comment by bzashev** [comment]
OK let me discuss with @rumen-yankov what the options are, but I am sure it will be tight on resources too.
Could someone take a lead on this implementation?

**Comment by hyfbeetle** [comment]
very good project. We use SQL, it could has bettle performance from web searching.

**Comment by bzashev** [comment]
We use SQL too but not Microsoft SQL. We do not have any performance issues with it
