### ISSUE TITLE
AsyncLocal null in different execution pipeline

### ISSUE THREAD

**Issue by 628426** [WebVella/WebVella-ERP#151]
When using the technique described here (thanks @rumen-yankov for providing the example)

https://github.com/WebVella/WebVella-ERP/blob/f4d5a173716ec2baf3696ac9f881a8f8543e028d/WebVella.Erp.ConsoleApp/Program.cs#L70

DbContext.Current is null, due to DbContext.current.Value being null.

https://github.com/WebVella/WebVella-ERP/blob/8642980055a2c1a569f7a1618eb1a321ea793f88/WebVella.Erp/Database/DbContext.cs#L17

Using AsyncLocal like this probably isn't recommended and it would be better if all the classes that relied on the DbContext took a reference to it in their constructor rather than try to look it up from AsyncLocal/ ThreadLocal/ HttpContext none of which I think would be perfect

Its possible and it fixes the problem - I know because I did it! (I couldn't move forward without this working)

Without automated tests its hard to know if its worked perfectly, all of my plugin code still ran and so on so I think its okay.  Are you happy with this sort of approach?  Do you want a pull request of it?

![image](https://user-images.githubusercontent.com/610683/91841636-0ae12c00-ec96-11ea-8ad7-db38caafe401.png)

**Comment by rumen-yankov** [comment]
Hey Nathan, I agree that using AsyncLocal is not the best idea, but it eliminates that 'noise' added by passing as arguments all context, connections and transactions objects to methods or constructors. 

I don't understand where you have problems with DbContext -> null , can you provide me a sample code ? In my example I create DbContext  and make EqlCommand execute inside its scope.

Also I am OK with your suggestion to add context to constructor as additional argument to some classes and store it into them. Please create a pull request with changes you need i will merge them.

**Comment by 628426** [comment]
> I don't understand where you have problems with DbContext -> null , can you provide me a sample code ? In my example I create DbContext and make EqlCommand execute inside its scope.

Thanks, the problem occurs when hosting WebVella inside a ASP.NET Core 3.1 Web Api running as a AWS Lambda function, using this technique https://github.com/WebVella/WebVella-ERP/blob/f4d5a173716ec2baf3696ac9f881a8f8543e028d/WebVella.Erp.ConsoleApp/Program.cs#L70

> Also I am OK with your suggestion to add context to constructor as additional argument to some classes and store it into them. Please create a pull request with changes you need i will merge them.

Thanks this is the pull request.
