### ISSUE TITLE
Case sensitive project directory

### ISSUE THREAD

**Issue by 628426** [WebVella/WebVella-ERP#158]
I now see 

https://github.com/WebVella/WebVella-ERP/tree/master/WebVella.ERP

and

https://github.com/WebVella/WebVella-ERP/tree/master/WebVella.Erp

Is this by design?

**Comment by rumen-yankov** [comment]
I still can't find why this happens. The folders and files names are Erp and can't understand why it commits it as all uppercase.

**Comment by rumen-yankov** [comment]
I deleted uppercase folder and project file.
