### ISSUE TITLE
Linkable Text Field and multivalue select

### ISSUE THREAD

**Issue by Amarjeet-L** [WebVella/WebVella-ERP#162]
#161 
1. Linkable Text Field -->
To facilitate allowing text in a wv-field-text and wv-field-select to be linked to a custom url.
Use case :
Consider two entities Order and Product, with a relationship between Order and Product. The Order LIst page displays a grid with a column displaying the product name. User needs to quickly and easily open the the product details page and see it's numerous fields ( The inventory for e.g.).
2. Multivalue Select - > 
 To facilate displaying multiple fields from the bound entity in the EntityRecordListToSelectOptionConverter datasource.
Use Case: In the order creation, the user needs to select a product based on its name or its sku and select the customer using their name or email or phone numer.

**Comment by rumen-yankov** [comment]
Pull request accepted.
