### ISSUE TITLE
The database could not be initialized successfully

### ISSUE THREAD

**Issue by heimi527** [WebVella/WebVella-ERP#167]
I'm a green hand for PostgreSql..
When i Run  WebVella.Erp.ConsoleApp To create necessary structure and data.  
But it aways Tips:   Unhandled exception. System.Exception: System error 10060. Entity: user. Field: created_on Message:User have no permissions to manipulate erp meta.

My PostgreSQL Version is 13..

Config.json for this

{
	"Settings": {
		"ConnectionString": "Host=localhost;Port=5432;Username=postgres;Password=test;Database=erp3_base;Pooling=true;MinPoolSize=1;MaxPoolSize=100;CommandTimeout=120;",
		"EncryptionKey": "BC93B776A42877CFEE808823BA8B37C83B6B0AD23198AC3AF2B5A54DCB647658",
		"Lang": "en",
		"Locale": "en-US",
		"TimeZoneName": "FLE Standard Time",
		"CacheKey": "", //if empty current date will be used 
		"DevelopmentMode": "true",
		"EnableBackgroungJobs": "false",
		"EnableFileSystemStorage": "false",
		"FileSystemStorageFolder": "\\\\192.168.0.2\\Share\\webvella-erp-files",
		"EmailEnabled": false,
		"EmailSMTPServerName": "",
		"EmailSMTPPort": "25",
		"EmailSMTPUsername": "",
		"EmailSMTPPassword": "",
		"EmailFrom": "",
		"EmailTo": "",
		"AppName": "WebVella Next",
		"NavLogoUrl": "",
		"SystemMasterBackgroundImageUrl": ""
	}
}

Can you instruct me how to configure the  PostgreSQL13 database  ,Thank You Very Much!!!

**Comment by rumen-yankov** [comment]
Hey, 
thanks for submitting the issue. I will take a look soon and try yo simulate the error.

**Comment by heimi527** [comment]
Hey,
Thanks for your reply,When you are free to help see how to solve the problem of database connection




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月12日(星期四) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WebVella/WebVella-ERP] The database could not be initialized successfully (#167)





 
Hey,
 thanks for submitting the issue. I will take a look soon and try yo simulate the error.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
