### ISSUE TITLE
can't login the WebVella.Erp.Site.Sdk

### ISSUE THREAD

**Issue by tiankongjintou** [WebVella/WebVella-ERP#170]
i init the database successfully. but i can't login with the email and the password which in the user table sheet.  
![微信图片_20210922152850](https://user-images.githubusercontent.com/7948351/134301006-4cf48f71-0594-48fa-916b-a0dbc58c65ff.png)

**Comment by tiankongjintou** [comment]
![1632295883(1)](https://user-images.githubusercontent.com/7948351/134301335-03ae2594-a273-4667-b03c-56494b7f3ba6.png)
![1632295903(1)](https://user-images.githubusercontent.com/7948351/134301398-7f532c78-cb68-4844-8b04-c7777a66f4f7.png)
thanks.

**Comment by bzashev** [comment]
Hey try erp@webvella.com with pass erp
for more info check this https://webvella.com/documents/developer/introduction/getting-started
