### ISSUE TITLE
This page isn’t working If the problem continues, contact the site owner. HTTP ERROR 405

### ISSUE THREAD

**Issue by Demtra** [WebVella/WebVella-ERP#171]
I set WebVella.Erp.Site as startup project
and build the solution 
![2021-11-27_142827](https://user-images.githubusercontent.com/41792440/143681337-671412d1-e4ba-4d71-963e-1bf9349d8692.png)

the browser popup and iam getting this.

This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 405

**Comment by sykyck** [comment]
Facing same issue any suggestions

**Comment by rumen-yankov** [comment]
Did you setup correct connection string to database ?  Initially it can be an empty database, but the database user should have rights to create initial structure, best it should be database owner.

**Comment by sykyck** [comment]
I  created an empty database
![WbVellaDatabase](https://user-images.githubusercontent.com/28142254/151191781-f66c3bc4-2df6-423e-9c1e-0843ddee9691.PNG)
![postgresuser](https://user-images.githubusercontent.com/28142254/151191874-37a5270e-5646-4c28-8cff-7e69a0143c71.PNG)
![Appsettings](https://user-images.githubusercontent.com/28142254/151191896-467d71d1-9418-47d2-9844-a3f1a475c651.PNG)
e

**Comment by rumen-yankov** [comment]
So, it looks database is OK.  How do you run the project , kestrel only or under IIS ?

**Comment by sykyck** [comment]
Using Visual studio 2019 community iis express

**Comment by rumen-yankov** [comment]
Can you try with kestrel only ? I am not sure why you have this problem, it's something specific with hosting configuration.
