### ISSUE TITLE
Update nugets and ASP core 6

### ISSUE THREAD

**Issue by papyr** [WebVella/WebVella-ERP#172]
Hello, a couple of simple requests can you please update to ASP core 6 with nugets and check in. The try-convert or upgrade-assitant does it automatically.

- [ ] Youtube -- Also please create some videos on creating
   - [ ]    Entities
   - [ ]    New Modules (and explain how and when to use the module approach)
- [ ]  Modules List/ Gallery _on your website_, of Add-ons/ Modules for Share sell modules on your site, by any others in your community like [orchard ](http://gallery.orchardproject.net/Packages/Modules) or WP or ABP. It would grow the community
- [ ] https://github.com/papyr/WorkflowEngine.NET
- [ ] https://github.com/KorzhCom/EasyData & EasyQuery

**Comment by rumen-yankov** [comment]
Hello, 
We have already updated projects to .NET 6 . Please specify if we missed something. Thanks in advance.

**Comment by papyr** [comment]
thanks, i will close, I had an old branch when I pulled.
