### ISSUE TITLE
PostgresSQL Connection Error - Change Database To MSSQL etc

### ISSUE THREAD

**Issue by RaoSaifUllah** [WebVella/WebVella-ERP#178]
Hi Sir,

I am having a problem connecting/initializing the database. UUID error. Can you please help me change the database to MSSql, I am not good with Postgres SQL.

Waiting for your kind reply.
Thanks

**Comment by bzashev** [comment]
Hey,
regrettably a change to MSSql is not in out plans as it is a paid database for larger projects and also the ERP is very closely tight to PostgreSQL at this moment.
