### ISSUE TITLE
Incorrect data type for the field types

### ISSUE THREAD

**Issue by bzashev** [WebVella/WebVella-ERP#18]
When in the field meta there is defaultValue, minValue, maxValue, decimalPlaces, dates and etc, 
the data is stored in the database as string, which is incorrect. It should be in the same data type as the expected field value. Example:
Percent field -> defaultValue,minValue and maxValue should be stored as decimal values are stored, not as strings

**Comment by bzashev** [comment]
The data type in the field meta json should also correspond. Example: defaultValue for a number should be returned as a number.

**Comment by rumen-yankov** [comment]
Cannot simulate the issue. Probably already fixed.
