### ISSUE TITLE
There is no functionality in the browser

### ISSUE THREAD

**Issue by konyashkingn** [WebVella/WebVella-ERP#186]
Hello!

I install according to the instructions - https://webvella.com/documents/developer/introduction/getting-started

I am installing a project "WebVella.Erp.Site" to run. The project is launch in the browser, but there is no functionality. Help.

Thank you.
<img width="820" alt="Снимок экрана 2023-02-16 в 16 15 08" src="https://user-images.githubusercontent.com/101064021/219374911-4202e40e-c348-4a39-b5cb-c32d9296b9e3.png">

**Comment by bzashev** [comment]
For future use, this is expected. It is on its platform stage so you need to add your own applications and cards will appear accordingly
