### ISSUE TITLE
"How-to use this code" section

### ISSUE THREAD

**Issue by 4lzn** [WebVella/WebVella-ERP#20]
would you give the "How-to use this code" section please.i downloaded the code, installed the mongodb but there were a lot of error about db so i am not able to run

**Comment by bzashev** [comment]
Hey, and welcome,
we will test the initial install and the automatic database configuration in the next couple of days. I will provide the howto till the end of this week. Hope that works for you.
Let me share some quick info though:
We work with a specific implementation of MongoDB -> TokuDb which has the benefit of having transactions. It is also also free and I will include some more info about it too. 
In general the idea is that once you setup the config.json file with the connection string to the database, the system check the state of the database and creates all necessary collections and records for its initial work.

**Comment by bzashev** [comment]
Hey again,
so we had a time slot and managed to prepare and test all the changes that are needed. The tested version is commited as of now. 
You problems and errors are probably related to the MongoDb type you were testing on. If you try with the TokuMX database all should be fine now.
I have also updated the HOW-to section (it was moved a little ahead in the readme text). There you should be able to find complete instructions.

Have in mind that we are still in the alpha phase with an intend to release the beta and RC until the end of the week.

All help is welcome and appriciated.

**Comment by 4lzn** [comment]
thank you. appreciated.
