### ISSUE TITLE
Edit list basic info

### ISSUE THREAD

**Issue by bzashev** [WebVella/WebVella-ERP#21]
There is a possible bug there. When I try to patch the list record with let's say new page size, it returns validation error with:
"errors":[{"key":"columns.relationName","value":null,"message":"Relation name is required!"},{"key":"columns.listName","value":null,"message":"List name is required!"}]

**Comment by rumen-yankov** [comment]
Cannot simulate it. bzashev checked it and cannot simulate it too.
