### ISSUE TITLE
Add filtering function when searching API

### ISSUE THREAD

**Issue by 28106830** [WebVella/WebVella-ERP#211]
Hello, it seems that this feature has been mentioned before
For example, I created a table, but the data administrator in this table can see everything, but different roles can see different filtering results. For example, salespeople can only see their own orders
Problem: Currently, when using the interface, I can complete the filtering function by writing code, but when using API/app/v3/en-US/ql, all data will be searched
What I expect is to be able to add HOOK when searching, and I can add specified filters in HOOK

**Comment by bzashev** [comment]
This sounds like the hooks we already have for record based hooks,
https://webvella.com/documents/developer/hooks/attach-to-api-hook we just do not have the Read type.
Will this work for your use case?

**Comment by 28106830** [comment]
对的，您的HOOK做的非常好，我测试过，只不过没有Read类型

**Comment by 28106830** [comment]
Yes, your HOOK can perform addition, deletion, and modification, but it does not implement query
My usage scenario is that my client does not use our platform, but instead uses API interfaces. However, if I provide them with an interface, they will be able to search for all the information in a certain table.
I have looked at the source code, and your data source is divided into two types. One is the database table, and the other is the code. For the database table, you can directly perform/app/v3/en-US/ql search, but cannot add filtering to the user. For example, the simplest one is that I want to open the user, but I want the user to only search for themselves. It can be achieved using the page interface, but it cannot be achieved using the API because my client does not follow my agreement to add username=themselves
I see that you have another data source of code type, but this is not a database table and cannot be searched using eql
So my requirement is: in API search, for users, they can use "Eql": "SELECT * FROM user", but our backend can add a restriction WHERE id=@ id "(except for administrators) for it, so that the security is high. Otherwise, I cannot give customers search permission

**Comment by 28106830** [comment]
/API/v3/en-US/meta/identity/This is also an API, but this restriction can only be used by administrators

**Comment by 28106830** [comment]
Even if not using API search
Your update hook can detect different update requirements in different modules
But searching is not possible, without HOOK, different modules can only be searched according to their own requirements, even if other modules require only the data rows they can view

**Comment by 28106830** [comment]
I originally wanted to work at eqlcommand Implement this function in Execute, but due to insufficient technology, it cannot be implemented
For example, the current user searches: select * from user
After determining that it is not an administrator: change to: select * from user WHERE id=@ id
Application scenarios:
1. Users can only see their own devices/orders (not implemented)
2. Users can only edit their own devices (HOOK implemented)
3. Users can only update their own device specifications (HOOK implemented)

**Comment by 28106830** [comment]
I can certainly add my own API search, but it breaks API consistency
But I need to disable/app/v3/en-US/ql separately according to the data table name, otherwise I cannot open this API, which is too dangerous

**Comment by bzashev** [comment]
Hey thanks for the detailed feedback, we will discuss this and get back to you with the result, options or questions ;)

**Comment by 28106830** [comment]
Thank you very much for your reply

**Comment by rumen-yankov** [comment]
If we implement filtering hook, it can be implemented 2 ways:
1. modify EQL before execute
2. modify results of EQL execution

In both ways hooks work at EqlCommand and will be for all EQL queries in system, which from my opinion will reflect to performance impact (may be low, may be high - depends on hooks implementation ) on every EQL request. Both ways of implementation are not very usable because developer will be provided with EQL as text and they will need to parse it to recognize what query do.

First way to developers will be provided with EQL as text and (List<EqlParameter>) list of parameters and will be able to modify both. This is not very usable because working with EQL as text will be hard. Developers will need to parse, change and rebuild EQL.

Second way is to provide developers a way to change the data result set of EQL query. Here is also a problem with paging. In example - lets say EQL query request from 1 page with page size 10. If there is a filtering hook, it may filter some records and return only X (<10) record. Paging is broken.

Do you have any better ideas how this filtering hook can be implemented ?

**Comment by 28106830** [comment]
671/10000
实时翻译
划译
Yes, I have tried to perform hook operations on Execute in eqlcommand, but my ability is limited and the implemented code is not very elegant
public EntityRecordList Execute()
{
    EqlBuilder eqlBuilder = new EqlBuilder(Text, CurrentContext, Settings);
    var eqlBuildResult = eqlBuilder.Build(Parameters); 
    bool hooksExists = RecordHookManager.ContainsAnyHooksForEntity(eqlBuildResult.FromEntity.Name);
    if (hooksExists)
    {
        List<ErrorModel> errors = new List<ErrorModel>();
        RecordHookManager.ExecutePreFindRecordHooks(eqlBuildResult.FromEntity.Name, this, errors);
        if (errors.Count > 0)
        {
            throw new EqlException(eqlBuildResult.Errors);
        }
        }
        ... ...
As you said, this will have an impact on performance, but the impact is not significant. We need to balance functionality and performance
But in the hook above, we only need to add an (old condition) and id=@ id to the 'where' condition in iPadOS reFindRecord to complete the basic filtering function

If you want to implement this feature, I hope you can give an example: ordinary users can only search for themselves in user

**Comment by 28106830** [comment]
In the above code, we do not need to manipulate the text of eql anymore, as you have already parsed the data results
Just need to operate on the search in the structure, I think it's eqlBuildResult Tree, but I'm not very familiar with it, so it's quite difficult to operate
I don't know if you are familiar with Odoo. In fact, it has created a dedicated interface in the data table: Security ->Record Rules, which can define the addition, deletion, query, and modification of specified data tables, and limit which user or user group it can be. Domain example: [('creat_uid ','=', user. id)]

**Comment by 28106830** [comment]
So I can use:/ Use API/v3/en-US/SQL to search, which saves you from having to write your own filtering criteria for each module
If we could add record rules like Odoo, that would be perfect
In table security, configuration for adding, deleting, querying, and modifying: [('resource_id.user_id', '=', user.id)]

**Comment by rumen-yankov** [comment]
Hey , thanks for your contribution. I am not familiar with Odoo and unfortunately at the moment have no time to take a look at it. But I will check your code and probably will add it to solution. I know its not a good idea to open AST for manipulation, but this is the easiest solution so far.

**Comment by rumen-yankov** [comment]
Hi,
Your code is merged in master. Nuget package WebVella.Erp 1.7.1 with changes is uploaded.  Thanks for contribution.

Note that your sample hook will not work for all entities written like it is. It is relevant only to User entity. Added changed example of your code in console project.
