### ISSUE TITLE
Hosting Problems with IIS

### ISSUE THREAD

**Issue by GittingGudAtIT** [WebVella/WebVella-ERP#212]
Hello,

I'm building an ERP system with your framework and I am not able to host it with IIS.
I published the WebVella.Erp.Site project.
When I set up a http binding with IP not assigned and  port e.g. 9001 and no host name it works as expected but when i enter a host name e.g. "www.myerp.com" it does not work.

Is there something I need to configure on application startup?
I've tried IWebHostBuilder.UseUrls("http://www.myerp.com:80") but did not change anything.

**Comment by bzashev** [comment]
Hey,
sorry to hear about the trouble. 
There is nothing that you need to setup in the configuration or StartUp for the domain to work.
The way we usually test the app on a new webhost is the following:
1. We launch it from WebVella.Erp.Site.exe and check the localhost:5000 if the site is opening and if any errors are reported in the console
2. if 1 is ok, this means that the publish is ok, we create the website in the IIS with the expected binding or spoofed domain on our local machines. If site opens the all is fine.
3. If 2 is not ok, check the iis log. There could be issue with the .net version. The system needs .9 or some other problem

In your case this is most probably a binding configuration problem. Check if you setup the folder correctly. It needs to point out to the folder that holds the webconfig file (not the wwwroot folder). Check if the IP is setup correctly to 80 and 443 for https if you have it. Check the application pool identity and if this identity has access to the folder contents.

**Comment by GittingGudAtIT** [comment]
Hello,
Sorry the problem was on my side.
Our internal DNS was not configured correctly.

**Comment by bzashev** [comment]
I am glad this got resolved ;)
