### ISSUE TITLE
Check a specific relation N:N case

### ISSUE THREAD

**Issue by bzashev** [WebVella/WebVella-ERP#24]
Is it possible to create a N:N relation that both the origin and the target fields are the record "id".

The case of creating an N:N relation between items ->  products <> related products

There is a possible easy workaround of creating a specific unique guid field just to support this relation and thus not needing the "id" from both sides of the realtion, but still it will be nice to be able to make it in the "logical" way

**Comment by rumen-yankov** [comment]
When relation is many to many type, then origin and target field is allowed to be the same.
