### ISSUE TITLE
Wrong validation error on entity record list update

### ISSUE THREAD

**Issue by bzashev** [WebVella/WebVella-ERP#40]
I am trying to update a "is default" property of an existing record list. I get a number of validation error which also are very confusing:
"There is already an item with such list name or id!"
"Wrong name. There is no list with such name or id!"

**Comment by bzashev** [comment]
another one in the same list validation,
when there are columns with fieldFromRelation and I am trying to make a match of a totally unrelated list details meta visibleColumnsCount it returns 
"Relation name is required!" - columns.relationName
"Field name is required!" - "columns.fieldName"

**Comment by rumen-yankov** [comment]
fixed
