### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by chiangim** [WebVella/WebVella-ERP#69]
Where to get the initial database to trial and test out this web ERP application?

**Comment by bzashev** [comment]
Hey,
the application itself creates the nominal database needed to start and run. This is done on application start. The only thing that you need is a clean install of PostgreSQL and a db user.

One note on the topic, we currently just switched from TokuMX to PostgreSQL. Just release the first build with the new database. The reason we have done that is because TokuMX lost its support, which is not a good thing.

If you need something more specific on how you can create more elements on app start, I can send you some code Snippets. But you can do all from the administration for sure.

One question, if I can, what kind of implementation you are targeting? I can help you out more if need to.

**Comment by bzashev** [comment]
By the way congrats on [bridge.net](https://github.com/bridgedotnet/Bridge). Impressive work!

**Comment by chiangim** [comment]
Hey, thanks for response. I also notice transition from TokuMX to PostgreSQL. Hence take a try on it since i am not familiar with Linux but more familiar with Windows.

I try to setup basic Accounting/Finance system for my dad small business usage. And i also notice WebVella is using latest technology and awesome UI. So would like to setup and take a oppurtunity to learn new technology.

Just setup note in GitHub is pretty simple and i am not even able to start from Visual Studio 2015.

**Comment by bzashev** [comment]
Hey,
thanks for the kind words. This is a currency most welcomed and appreciated in the open source world.
So I have a good news and a bad news. 
The good news is that this is exactly what we are building - a good, modern, free and opensource system, for the small and medium business. The bad news is that we are still in alpha and we expect many things to be added and changed in the next months. This is the reason why we are missing some end user ready packages and documentation around them. We plan to have them, but once we finish off the things we want to have in the v.1 build.
If you want to test it how it is currently (it is still very capable platform and has a lot in it), and do not have a Visual Studio, I can build a package for you, and send you some instructions how to use it. 
Also I can setup a demo where you can access and play with what we have now. If you decide to start building the app you need, it still can happen, and I will gladly help you out, Basically almost all you need is there or almost there. What is left is some configuration to be made.
If you are interested just say so and we will plan it and do it. 
Again thanks for the kind words.

**Comment by chiangim** [comment]
Hi,

I am able to setup DNX environment now and able to start debug in Visual Studio 2015 Community. However i stuck at database setup. It need me already have initial database with tables: system_settings(primary look at version and upgrade database), entities, entity_relations, rec_role, rec_user etc. 

Below method, **entity.Fields** alway return 5 count of result(default columns) when users table is created. Additional column that added on runtime will always failed.

                public void CreateRecordField(string entityName, string fieldName, object value)
		{
			string tableName = RECORD_COLLECTION_PREFIX + entityName;

			DbEntity dbEntity = DbContext.Current.EntityRepository.Read(entityName);
			Entity entity = dbEntity.MapTo<Entity>();
			Field field = **entity.Fields**.FirstOrDefault(f => f.Name.ToLowerInvariant() == fieldName.ToLowerInvariant());
			DbRepository.CreateColumn(tableName, field.Name, field.GetFieldType(), false, ConvertDefaultValue(field.GetFieldType(), value), field.Required);
		}

If you can send me pre-seed database to test on UI and able to let me do some configuration on web screen. I believe the application will be ready after entities setup.

This application looks like modeling the entity first, then construct or execute the ERP/CRM application  on runtime. it also stored the table structure into json field at entities table. 

Impressive & great work!

**Comment by bzashev** [comment]
Hey, 
this is a bug, we are just fixing it. Later today it will be fixed. Let's say 10 hours as we are working on it. 
For the rest, yes you have point exactly what it is doing. 
What needs some further extending is to add calculative fields types, so you can present calculated data to the end user.
On a implementation I am currently making (I work on 3 now so it will be nice to chat with someone that is doing the same :) ), there was also a need for the record views to be far more customized by providing completely custom template of the dynamic html, and just reusing the data from the view's json. We are almost done on this, but we will need a couple of days to clean the database change stuff as it is quite fresh.
Thanks for you support and interest
Boz

**Comment by bzashev** [comment]
We have fixed the db issue, but wait a little longer as  I have updated the angular to the newest version and there are some problems here and there

**Comment by bzashev** [comment]
Ok you can get and try the process now

**Comment by CoCEmu** [comment]
Hello,
thank you for this good project
i have a question,
i download all code and run .sln file and then i install PostgreSql
i create database with name erp3_base and set password for postgres and i edit config.json file.
buy when i run this project i got error with database :
`System error 10060. Entity: user. Field: userName Message:42703: column "username" does not exist   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at WebVella.Erp.Database.DbRepository.CreateColumn(String tableName, String name, FieldType type, Boolean isPrimaryKey, Object defaultValue, Boolean isNullable, Boolean isUnique, Boolean overrideNulls, Boolean useCurrentTimeAsDefaultValue, Boolean generateNewId) in C:\Users\Server\Desktop\WebVella-ERP-master\WebVella-ERP-master\WebVella.ERP\Database\DbRepository.cs:line 245
   at WebVella.Erp.Database.DbRepository.CreateColumn(String tableName, Field field) in C:\Users\Server\Desktop\WebVella-ERP-master\WebVella-ERP-master\WebVella.ERP\Database\DbRepository.cs:line 179
   at WebVella.Erp.Database.DbRecordRepository.CreateRecordField(String entityName, Field field) in C:\Users\Server\Desktop\WebVella-ERP-master\WebVella-ERP-master\WebVella.ERP\Database\DbRecordRepository.cs:line 308
   at WebVella.Erp.Api.EntityManager.CreateField(Guid entityId, InputField inputField, Boolean transactional) in C:\Users\Server\Desktop\WebVella-ERP-master\WebVella-ERP-master\WebVella.ERP\Api\EntityManager.cs:line 1003'
`

**Comment by rumen-yankov** [comment]
Hey Mate, 
You probably entered wrong connection string.  The connection string we use don't set "username". Use "User Id" instead.

**Comment by CoCEmu** [comment]
Thank you
i dont change user id to username 
but i just create a database and input to configs.json file , and if i change user id or password i got error in auth.
its the first time of installation and my table dose not created yet!

**Comment by CoCEmu** [comment]
System.Exception: 'System error 10060. Entity: user. Field: userName Message:The field was not created. An internal error occurred!'
i got the error when in changed "DevelopmentMode" to "false",

**Comment by rumen-yankov** [comment]
Do database user (you use) have enough right to create tables and columns ?
