### ISSUE TITLE
Refferences issues

### ISSUE THREAD

**Issue by net4u** [WebVella/WebVella-ERP#83]
Hi,

Maybe is a dumb situation, but I encounter this after opening solution, and I am not clear what might be
(I am on VS 2015 with all updates, and I do nugget packages restore/update).

![2016-05-06 3](https://cloud.githubusercontent.com/assets/255743/15070246/b7398c6a-138b-11e6-876b-db7380b0e8c8.png)

**Comment by bzashev** [comment]
Hey,
from what I see some packages are at 1.0.0-rc-1-final, some are at newer version. What I am testing and running in the moment is at rc1-final. Let me look around how is it with the rc2. Probably just all packages need to be upgraded to rc2 and not to have some at rc1 and some at rc2.
My collegue, Rumen, which is much more experienced in the server side will test and write you in the next 24 hours.
Thanks for the great feedback.

**Comment by bzashev** [comment]
Hey I fixed the package version to rc1, could you try how it is now. It should be OK. We will check about the possible update to the rc2 and get back to you

**Comment by net4u** [comment]
thank you, I will come back with comments later this afternoon

**Comment by net4u** [comment]
I confirm that now it build without errors.  Thank you guys.
off topic: Is there a sql script for populate the database?

**Comment by net4u** [comment]
Now I have this:
![2016-05-06 4](https://cloud.githubusercontent.com/assets/255743/15072903/b60aada2-139e-11e6-91e4-7f3af84610b6.png)

**Comment by bzashev** [comment]
Hey,
1. About the database - the ERP itself creates all it needs if the database is empty. All the plugins work the same way, but yet they are still in development.
2. About the error - it is in one of the plugins,
Try to go to the dlls in the binaries  folder of both the webvella-crm and webvella-project. Right click on the dll files and click the unblock button.

**Comment by net4u** [comment]
Sorry if I bother, it seems to me that is a new kind of platform and I am not familiar with.
I build the solution. I find that in artifacts subfolder(s) the layout of folders is a little bit different from regular MVC structure. 
So if I want instead of running from VS to publish on my test webserver, what I have to copy?

**Comment by bzashev** [comment]
It is brand new for all of us :). You need all the folders that are produced by the publish process. The different stuff here is that you will need to point the site root to the wwwroot. The rest is still needed though. 
Just have in mind that when preparing the webserver currently you will probably need to install HttpPlatformHandler v1.2. This is needed for the latest rc1 and above. 
There is also a new webserver Kestrel with this platform but IIS is still good. 
My advice is to read around google but to set the search to show you results just in the past 6 months. A lot has changed recently

**Comment by bzashev** [comment]
From what I see just some libraries were released before the mvc general rc2 release. So I am closing this and submit a new one for any problems you may have
