### ISSUE TITLE
RC2 update?

### ISSUE THREAD

**Issue by DaveConsulting** [WebVella/WebVella-ERP#90]
Wouldn't be better to upgrade to RC2 as soon as possible?

**Comment by bzashev** [comment]
I agree, and we are planing too. It is just not the small incremental update we were expecting. Lot's of things are changed so we will need some time, but we are surely going there :)

**Comment by bzashev** [comment]
I closed it by mistake :(

**Comment by bzashev** [comment]
Updated to RC2
