### ISSUE TITLE
Setting up Development Environment

### ISSUE THREAD

**Issue by tympaniplayer** [WebVella/WebVella-ERP#94]
The section in the [readme](https://github.com/WebVella/WebVella-ERP#how-to-use-this-code) for how to use the code I believe is not quite verbose enough. If you could would you please add:

1. What version of Visual studio (e.g. update 3 is required or not)
2. How to build using and make sure it uses .NET core and not .NET 4.6
3. How to setup the site (Do you do it in IIS or just run it?)

I realize this is a bit to ask for, however maybe in my spare time I can get the project running, and enhance the readme myself.

**Comment by bzashev** [comment]
Hey,
thanks for looking into this. What we are currently using is Visual Studio Update 3. Whether it is require or not I cannot say in the moment, but the fact that MS released both asp.net core 1.0 and the update 3 in the same moment probably means this is the best tested case. But still did not find anything in the release note https://blogs.msdn.microsoft.com/visualstudio/2016/06/27/visual-studio-2015-update-3-and-net-core-1-0-available-now/
To build and run the project you will need asp.net core 1.0 nothing else. The core 1.0 uses always Kestrel as a webserver. IIS is now just a proxy. There is a lot of materials on that.
Setting up the site has two things to look for:
1. Running from Visual Studio -> you just make WebVella.ERP.Web a starup project and hit run. All should be straight forward from this moment. It will run kestrel with IIS Express as a proxy.
2. Running from within IIS webserver (not IIS Express). You will need to publish the project and copy the files. There are some specifics on how to setup the site, the application pool mode and etc., but there are a lot of excellent how-to's. We use the standard way as all the asp.net core 1 applications.

**Comment by bzashev** [comment]
Hope the above comment helps. You are most welcome to extend the Readme file. Send us what you came up with and we will look at it asap.
Thanks
