### ISSUE TITLE
ReactJS or Angular 2?

### ISSUE THREAD

**Issue by bzashev** [WebVella/WebVella-ERP#96]
Hey guys, 
what is your opinion on the following matter.
For the next year we are planning on upgrading the JS framework from the current Angular 1. During the research process we came to conclusion that we should not dismiss the alternative of switching to ReactJS lightly, as it has many advantages too over Angular 2. 
It will be complete rewrite in all cases because of the Angular 2 move of google (which will lost a lot of time in the first place).
Could you share your opinion in what we shall choose - Angular 2 or ReactJs

**Comment by ultimatemm** [comment]
Angular 2. +1

**Comment by bzashev** [comment]
ReactJs / Redux +1

**Comment by bzashev** [comment]
After a lot of research and testing of what is best for us, the team chose ReactJs. 
The call was very close, but based on the current state of both projects and our needs this is the best way forward. 
The way the migration will be done, we will make another admin interface that will work side by side for a time with the current one. One of the new abilities that react will provide is to make the administration CMS side much stronger. A lot of ideas, very little time as always

**Comment by nhannv** [comment]
Hi bzashev,
Sorry if I shouldn't comment on closed issue. Thank you for great work. Could you tell me when "move to ReactJS" will be done (in planning)?
Thanks

**Comment by bzashev** [comment]
Hey, no worries. Thanks for your feedback. Our plans is the work to begin in Q1 2017 and to be finished in Q2 2017.

**Comment by mercury838** [comment]
Hi bzashev,
Do we still stick with the plan AngularJS to React?

**Comment by bzashev** [comment]
In general yes, we also now review the ability to increase the CMS part of the platform too, so we have more tools to build different pages with different layouts.
The latest we are reviewing is to migrate from Angular to React and from one pager to MVC with react, and to focus on more development focus when creating pages. 
Things are getting really nice.

**Comment by samdubey** [comment]
Have anyone considered Vue.Js ?

**Comment by bzashev** [comment]
Yes we did. Looks like a good solution. It is not 100% decided to be React as we are currently looking into some changes in the way the UI will be build, based on our experience with building several big projects on it

**Comment by ShaneZhengNZ** [comment]
@bzashev It has been 3 years since the last comment about this issue. Just wondering any React progress yet? I am very interested in the project and planning to use it for my organisation if possible. However, we would like to build the UI with React. If there are existing React work done for this project, then it will make things much easier, otherwise, I might decide to work on it.

**Comment by bzashev** [comment]
Hey, the most recent on this is that we will go the Blazor way. Most probably Blazor WASM way. We have started creating Blazor components already (WebVella.Pulsar). The transition will start once .Net 5.0 is released.
